config/routes.rb
Sleepmonster::Application.routes.draw do
  devise_for :users
  resources :children, only: [:index, :new, :create, :edit, :update] do
    resources :sleep_blocks, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        get "/for/:date", to: "sleep_blocks#for_date", as: "for_date"
        get "/page/:page", to: "sleep_blocks#paged", as: "paged"
      end
    end
  end

  get "/mobile", to: "application#mobile"
  get "/fullsite", to: "application#fullsite"

  root to: "welcome#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

end

app/views/welcome/index.html.haml
- if !user_signed_in?
  .clouded
    .copy
      %h1 Welcome
      %p Tired Tots helps you track your child's sleep habits so that you can better understand the link between the sleep your child is getting and her behavior.
      To get started,
      = link_to "sign up", new_user_registration_path
- else
  - if current_user.children.empty?
    %p
      To get started,
      = link_to "add a child", new_child_path
  - else
    .children_header
      %h1
        Your children
        = link_to "(manage)", children_path
    %ul.children
      - current_user.children.each do |child|
        %li.child
          .child_name= child.name
          %p= link_to "Sleep journal", child_sleep_blocks_path(child)
          - if child.recent_tracked_days.count > 1
            %p Average sleep for the past two weeks:
            .chart_data
              %dl
                %dt Average
                %dd= child.recent_sleep_average_in_hours
              %table
                %thead
                  %tr
                    %th day
                    %th total
                %tbody
                  - child.recent_tracked_days.each do |tracked_day|
                    %tr
                      %td= tracked_day.for_date.to_s(:msd)
                      %td= number_with_precision(tracked_day.sleep_total_in_hours, :precision => 1)
          - else
            Not enough data to chart yet.

app/views/welcome/index.mobile.haml
- if !user_signed_in?
  - content_for :toolbar do
    %h1 Home
  Tired Tots helps you track your child's sleep habits so that you can better understand the link between the sleep your child is getting and her behavior.
- else
  - content_for :toolbar do
    %h1 Home
    = link_to 'Add child', new_child_path, class: 'ui-btn-right', 'data-icon' => 'plus'
  - if current_user.children.empty?
    To get started, add a child.
  - else
    %ul(data-role='listview')
      - current_user.children.order(:name).each do |child|
        %li
          = link_to child.name, child_sleep_blocks_path(child)
          = link_to 'edit child', edit_child_path(child), 'data-icon' => 'gear'