config/routes.rb
Sleepmonster::Application.routes.draw do
  devise_for :users
  resources :children, only: [:index, :new, :create, :edit, :update] do
    resources :sleep_blocks, only: [:index, :new, :create, :edit, :update, :destroy] do
      collection do
        get "/for/:date", to: "sleep_blocks#for_date", as: "for_date"
        get "/page/:page", to: "sleep_blocks#paged", as: "paged"
      end
    end
  end

  get "/mobile", to: "application#mobile"
  get "/fullsite", to: "application#fullsite"

  root to: "welcome#index"
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US" class=page_class)
  %head
    %title Tired Tots
    %meta(charset="UTF-8")
    = stylesheet_link_tag "public"
    = stylesheet_link_tag "mobile" if mobile_site_requested?
    = yield :stylesheets
    = javascript_include_tag 'application.js'
  %body
    #container
      %header
        %section
          %nav#primary
            = link_to(image_tag('logo.gif'), root_path, :title => 'home')
          %nav#secondary
            - if user_signed_in?
              Signed in as
              %em= current_user.email
              |
              = link_to "profile", edit_user_registration_path
              |
              = link_to "sign out", destroy_user_session_path
            - else
              = link_to "sign up", new_user_registration_path
              |
              = link_to "sign in", new_user_session_path

      #main
        %p.notice= notice
        %p.alert= alert

        = yield

      #root-footer

    #footer
      .content
        .attribution
          = link_to "Wes Gibbs", "http://wesgibbs.me"
          made this!
        - if mobile_user_agent?
          .mobile_site
            = link_to "View the mobile site", mobile_path
        .notices
          &copy;
          = Date.today.year
          Wes Gibbs

app/views/layouts/application.mobile.haml
!!! 5
%html(lang="en-US" class=page_class)
  %head
    %title Tired Tots
    %meta(charset="UTF-8")
    = stylesheet_link_tag "http://code.jquery.com/mobile/1.0a3/jquery.mobile-1.0a3.min.css", "mobile.css"
    = javascript_include_tag "http://code.jquery.com/jquery-1.5.min.js"
    = yield :pre_mobile_load
    = javascript_include_tag "http://jquerymobile.com/test/js/" # http://vurl.me/AECL
  %body
    .page(data-role='page' data-url="#{data_url}")
      .header(data-role='header')
        = yield :toolbar

      .content(data-role='content')
        = yield

      .footer(data-role='footer' data-id='myfooter' data-position='fixed')
        .navbar(data-role='navbar')
          %ul
            - if user_signed_in?
              %li= link_to 'Home', root_path, 'data-icon' => 'home', rel: 'external'
              %li= link_to 'Sign Out', destroy_user_session_path, 'data-icon' => 'delete', rel: 'external'
            - else
              %li= link_to "Sign Up", new_user_registration_path, 'data-icon' => 'plus', rel: 'external'
              %li= link_to "Sign In", new_user_session_path, 'data-icon' => 'home', rel: 'external'
            %li= link_to "Full Site", fullsite_path, 'data-icon' => 'forward', rel: 'external'